homeassistant: true
permit_join: false
frontend:
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto:1883'
  user: '!secret user'
  password: '!secret password'
serial:
  adapter: deconz
  port: /dev/ttyAMA0
advanced:
  availability_timeout: 120
devices:
  '0x588e81fffe9c3994':
    friendly_name: bedroom_main_light_rgb
  '0x842e14fffe1e20d5':
    friendly_name: bedroom_bed_left_band
  '0x842e14fffe15fbe6':
    friendly_name: bedroom_bed_right_band
  '0x00178801082626bf':
    friendly_name: homeoffice_main_light
  '0x0017880108b832b9':
    friendly_name: livingroom_dinnertable_light
  '0x001788010826273a':
    friendly_name: livingroom_couch_light
  '0x0017880108f84895':
    friendly_name: hue_dimmer_switch_01
  '0x0017880104c4ed98':
    friendly_name: corridor_pictures_light
  '0x00178801093bb8a3':
    friendly_name: corridor_cabinet_light
  '0xbc33acfffe86580c':
    friendly_name: homeoffice_motion_sensor
  '0x00158d0006bee32a':
    friendly_name: livingroom_thp_sensor
  '0x00158d0006b89def':
    friendly_name: childrenroom_thp_sensor
  '0x00158d0006bfa0b9':
    friendly_name: boilerroom_thp_sensor
  '0x00158d0006c5f20d':
    friendly_name: laundry_thp_sensor
  '0x00158d0006b89dab':
    friendly_name: bedroom_thp_sensor
  '0x00158d0006beaea7':
    friendly_name: pantry_thp_sensor
