version: "3.0"
services:
  ### home assistant
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ~/docker/mosquitto/config:/mosquitto/config
      - ~/docker/mosquitto/data:/mosquitto/data
      - ~/docker/mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: always
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - mosquitto
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    ports:
      - "8124:8080"
    volumes:
      - ~/docker/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro

  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    restart: always
    network_mode: "host"
    depends_on:
      - zigbee2mqtt
    devices:
      - /dev/serial/by-id/usb-EnOcean_GmbH_EnOcean_USB_300_DC_FT50B8B0-if00-port0:/dev/serial/by-id/usb-EnOcean_GmbH_EnOcean_USB_300_DC_FT50B8B0-if00-port0
    volumes:
      - ~/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro

  ### pihole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: <pw>
    volumes:
      - ~/docker/pihole/:/etc/pihole/
      - ~/docker/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: always

  ### monitor
  docker2mqtt:
    image: serowy/docker2mqtt:latest
    container_name: docker2mqtt
    restart: always
    depends_on:
      - mosquitto
    volumes:
      - ~/docker/docker2mqtt/config:/docker2mqtt/config
      - ~/docker/docker2mqtt/logs:/docker2mqtt/logs
      - /var/run/docker.sock:/var/run/docker.sock

  ### update
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=82800
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

  ### backup

  # https://rclone.org/
  # rclone mount --allow-other --vfs-cache-mode writes gdrive: /backup
  # rclone sync /backup gdrive:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    volumes:
      - ~/backup:/backup:shared
      - ~/docker/rclone:/config/rclone
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN

  # https://borgbackup.readthedocs.io/
  # borg init --encryption=repokey-blake2 --storage-quota 15G /backup
  borg:
    image: hotio/borg:latest
    container_name: borg
    volumes:
      - ~/backup:/backup
      - ~/docker:/source
      - ~/docker/borg:/data
    environment:
      BORG_BASE_DIR: /data
      BORG_PASSPHRASE: mL2VJKz8UmGi3nH39og4FmU28hBagAniQVoZZms8ybPYHkGcKgkL8QQyizJGTrtk
