name: "ci"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config --local user.email "serowy@hotmail.com"
          git config --local user.name "aserowy"
          git submodule update --init --recursive

      - name: install nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: check flake
        run: |
          nix build
          nix flake check -v --show-trace
        timeout-minutes: 90
